<?php  //[STAMP] 665b6e9d514787c0c7153a9b9e642bc5
namespace Stigma\Nagios\_generated;

// This class was automatically generated by build task
// You should not change it manually as it will be overwritten on next build
// @codingStandardsIgnoreFile

use Stigma\Nagios\Helper\Functional;

trait FunctionalTesterActions
{
    /**
     * @return \Codeception\Scenario
     */
    abstract protected function getScenario();

    
}
