<?php  //[STAMP] 1a118f0cce3bf931548445a248855135
namespace Stigma\ObjectManager\_generated;

// This class was automatically generated by build task
// You should not change it manually as it will be overwritten on next build
// @codingStandardsIgnoreFile

use Stigma\ObjectManager\Helper\Functional;

trait FunctionalTesterActions
{
    /**
     * @return \Codeception\Scenario
     */
    abstract protected function getScenario();

    
}
