<?php  //[STAMP] 8a4a45cd55fdb958d7501ddf56c1884a
namespace Stigma\ObjectManager\_generated;

// This class was automatically generated by build task
// You should not change it manually as it will be overwritten on next build
// @codingStandardsIgnoreFile

use Stigma\ObjectManager\Helper\Functional;

trait FunctionalTesterActions
{
    /**
     * @return \Codeception\Scenario
     */
    abstract protected function getScenario();

    
}
