<?php  //[STAMP] ec985c7f5fc4064831128d5a802d7a77
namespace Stigma\CommandBuilder\_generated;

// This class was automatically generated by build task
// You should not change it manually as it will be overwritten on next build
// @codingStandardsIgnoreFile

use Stigma\CommandBuilder\Helper\Functional;

trait FunctionalTesterActions
{
    /**
     * @return \Codeception\Scenario
     */
    abstract protected function getScenario();

    
}
